---
title: "aged timecourse bulkRNA-seq "
output: html_document
---


```{r, include= F}
library(tidyverse)
library(glue)
library(DESeq2)
library(here)
library(tximport)
library(RColorBrewer)
library(vsn)
library(ComplexHeatmap)
library(biomaRt)
```

Read in experimental metadata
```{r}
data_dir <- here("kallisto_out_merged/")
metadata_path <- here("metadata_merged.csv")
list.files(data_dir)


exp_metadata <- read.csv(metadata_path, header = T)

# named_runs <- exp_metadata %>% deframe
```



Differential expression on relevant conditions
```{r}
dds <- readRDS(here("data/bulkrna_dds_collapsed_before.rds"))

test_names <- paste0("age_",c("6mo","17mo"),"_vs_P30")

res_list <- map(test_names, function(name){
  tbl <- read.csv(paste0(here("results/diff_exp_collapsed_before/"), name,".csv"), row.names = 1)
})

clip_nlog10p <- 10
sigthresh_nlog10p <- -log10(.05)
res_df <- map_df(test_names, function(name){
  tbl <- read.csv(paste0(here("results/diff_exp_collapsed_before/"), name,".csv"), row.names = 1)
  tbl <- tbl %>% mutate(condition = name,
                        nlog10p = ifelse(-log10(padj) > clip_nlog10p, clip_nlog10p, -log10(padj)),
                        nlog10p_clipped = ifelse(-log10(padj) > clip_nlog10p, T, F ))
  return(tbl)
})


```



Get biomart annotations for gene short names
```{r}
library(biomaRt)
#get gene names, make sure to use the right ensembl archive for genome used for alignment
#listMarts() 
ensembl <- useMart("ensembl")
datasets <- listDatasets(ensembl)
ensembl <- useDataset("mmusculus_gene_ensembl",mart=ensembl)

gene_id_trimmed <- rownames(dds)
gene_description <- getBM(attributes = c("ensembl_gene_id_version","external_gene_name","description","chromosome_name"),
                   filters = "ensembl_gene_id", values =gene_id_trimmed,  mart = ensembl)

geneid2name <- gene_description[,c("ensembl_gene_id_version", "external_gene_name")] %>% 
  mutate(ensembl_gene_id_trimmed = str_split_fixed(ensembl_gene_id_version, "\\.", 2) %>% .[,1])

gene_ids <- geneid2name %>% mutate(ensemblgene_id = ensembl_gene_id_version)
```
```{r}
pcut <- 0.05
#all genes that are DE in either condition
diff_genes <-res_df %>% filter(padj < pcut) %>% pull(ensemblgene_id) %>% unique()

res_df_filtered <- res_df %>% filter(ensemblgene_id %in% diff_genes)
res_df_filtered_wide <- res_df_filtered  %>%
  dplyr::select(c(ensemblgene_id, padj, nlog10p, condition, log2FoldChange)) %>%
  pivot_wider(names_from = condition, values_from = c(padj, log2FoldChange, nlog10p)) %>% 
  mutate(both_sig = padj_age_6mo_vs_P30 < pcut & padj_age_17mo_vs_P30<pcut,
         doe_17mo_vs_P30 = sign(log2FoldChange_age_17mo_vs_P30),
         doe_6mo_vs_P30 = sign(log2FoldChange_age_6mo_vs_P30),
         direction_consistent = (doe_17mo_vs_P30 == doe_6mo_vs_P30),
         direction = ifelse(direction_consistent, sign(log2FoldChange_age_6mo_vs_P30), paste(doe_6mo_vs_P30,doe_17mo_vs_P30, sep = ","))) 

#for genes significant for both timepoints, what are the direction of effects?
res_df_filtered_wide %>% filter(both_sig == T) %>% pull(direction) %>% table

#for genes significant for at least one timepoint, what are the direction of effects (over both timepoints)?
res_df_filtered_wide %>% pull(direction) %>% table

genes_down <- res_df_filtered_wide %>% filter(both_sig == T, direction == -1) %>% pull(ensemblgene_id) 
genes_up <- res_df_filtered_wide %>% filter(both_sig == T, direction == 1) %>% pull(ensemblgene_id) 

```

```{r}


ggplot(res_df_filtered_wide,aes(x = nlog10p_age_6mo_vs_P30, y=nlog10p_age_17mo_vs_P30 )) + geom_point(size = I(0.01))+ xlab("6mo vs P30 nlog10p") + ylab("17mo vs P30 nlog10p") + geom_hline(yintercept = sigthresh_nlog10p, linetype = "dashed", color = "red")+ geom_vline(xintercept = sigthresh_nlog10p, linetype = "dashed", color = "Red")

ggplot(res_df_filtered_wide,aes(x = log2FoldChange_age_6mo_vs_P30, y=log2FoldChange_age_17mo_vs_P30, color = interaction(both_sig,direction, sep = ":" ))) + geom_point(size = I(0.01))+ xlab("6mo vs P30 log2FC") + ylab("17mo vs P30 log2FC") + ggtitle("Subset of genes for which at least one condition is signficantly DE")+ guides(colour = guide_legend(override.aes = list(size=5)))
# 
# diff_genes_df <- res_df %>% group_by(condition) %>% mutate(sig = padj < pcut, lfc_direction = ifelse(log2FoldChange > 0, "up", "down")) %>% filter(ensemblgene_id %in% diff_genes) 

```
```{r}
genes_both_sig <- res_df_filtered_wide %>% filter(both_sig == T) %>% pull(ensemblgene_id)
#diff_genes has genes that are DE in at least one timepoint

#clustering on LFC
#on diff genes
log2fc_mat <- res_df_filtered_wide %>% dplyr::select(ensemblgene_id, log2FoldChange_age_6mo_vs_P30, log2FoldChange_age_17mo_vs_P30) %>% mutate(log2FoldChange_age_P30_vs_P30 = 0) %>% column_to_rownames(var = "ensemblgene_id") %>% as.matrix()

# clusters <- hclust(dist(log2fc_mat))
# plot(clusters)

nclust <- 8
cluster.kmeans <- kmeans(log2fc_mat, centers = nclust)
cluster_df <- cluster.kmeans$cluster %>% enframe(name = "ensemblgene_id", value = "cluster.k.8") %>% add_count(cluster.k.8) %>% mutate(cluster_title = paste0("cluster ",cluster.k.8, " (n=",n,")"))

log2fc_long <- res_df_filtered %>% full_join(cluster_df) %>% dplyr::select(external_gene_name, ensemblgene_id, log2FoldChange, condition) %>% mutate(condition = case_when(condition == "age_6mo_vs_P30" ~ "6mo", condition == "age_17mo_vs_P30" ~ "17mo"))

p30_df <- log2fc_long %>% dplyr::select(external_gene_name, ensemblgene_id) %>% unique %>% mutate("log2FoldChange" = 0, condition = "P30")

log2fc_long <- rbind(log2fc_long, p30_df) %>% mutate(condition = factor(condition, levels = c("P30","6mo","17mo"))) %>% full_join(., cluster_df)   
dummy_df <- log2fc_long %>% dplyr::select(-cluster_title)
ggplot(log2fc_long, aes( x = condition, y = log2FoldChange, group = ensemblgene_id)) + geom_line() + facet_wrap(~cluster_title, scales = "free_y") + ylab("log2FC relative to P30") 

ggplot(log2fc_long, aes( x = condition, y = log2FoldChange, group = ensemblgene_id)) + geom_line(data = dummy_df, color = "grey50")  + geom_line() + facet_wrap(~cluster_title) 

```

```{r}
#clustering on shrinkage LFC
resLFC6mo <- lfcShrink(dds,coef = "age6mo", type="apeglm") %>%
  as.data.frame() %>% .[, "log2FoldChange", drop = F] %>%
  rownames_to_column(var = "ensemblgene_id")
resLFC17mo <- lfcShrink(dds,coef = "age17mo", type="apeglm") %>%
  as.data.frame() %>% .[, "log2FoldChange", drop = F] %>%
  rownames_to_column(var = "ensemblgene_id")

resLFC <- full_join(resLFC6mo,resLFC17mo, suffix = c(".6mo",".17mo"), by = "ensemblgene_id")
ggplot(resLFC, aes(x = log2FoldChange.6mo, y= log2FoldChange.17mo)) + geom_point()

#on diff genes
log2fc_mat <- resLFC %>% filter(ensemblgene_id %in% diff_genes) %>%
  mutate(log2FoldChange.P30 = 0) %>% column_to_rownames(var = "ensemblgene_id") %>% as.matrix()

# clusters <- hclust(dist(log2fc_mat))
# plot(clusters)

nclust <- 8
cluster.kmeans <- kmeans(log2fc_mat, centers = nclust)
cluster_df <- cluster.kmeans$cluster %>% enframe(name = "ensemblgene_id", value = "cluster.k.8") %>% add_count(cluster.k.8) %>% mutate(cluster_title = paste0("cluster ",cluster.k.8, " (n=",n,")"))

log2fc_long <- log2fc_mat %>% as.data.frame() %>%
  rownames_to_column(var = "ensemblgene_id") %>%
  full_join(cluster_df) %>%
  pivot_longer(!c(ensemblgene_id, n, cluster_title, cluster.k.8), values_to = "logFCshrink", names_to = "condition") %>%
  mutate(condition = case_when(
    condition == "log2FoldChange.6mo" ~ "6mo",
    condition == "log2FoldChange.17mo" ~ "17mo", 
    condition == "log2FoldChange.P30" ~ "P30"
  ))%>%
  mutate(condition = factor(condition, levels = c("P30","6mo","17mo")))

  
dummy_df <- log2fc_long %>% dplyr::select(-cluster_title)
ggplot(log2fc_long, aes( x = condition, y = logFCshrink, group = ensemblgene_id, alpha = transparency_corrected)) + geom_line(color = "black") + facet_wrap(~cluster_title, scales = "free_y") + ylab("log2FC shrinkage estimates relative to P30") 

ggplot(log2fc_long, aes( x = condition, y = logFCshrink, group = ensemblgene_id, alpha = transparency_corrected)) + geom_line(data = dummy_df, color = "grey50")  + geom_line() + facet_wrap(~cluster_title) 
```

```{r}
res <- results(dds, name = "age17mo")
res %>% head
summary(res)

resultsNames(dds)
resLFC <- lfcShrink(dds,coef = "age17mo", type="apeglm")

assertthat::assert_that(all(rownames(res) == rownames(resLFC)))
qplot(res6mo$log2FoldChange, resLFC17mo$log2FoldChange, color = res$baseMean) + scale_color_viridis_c(name = "res$baseMean", trans = "log")
qplot(res$log2FoldChange, resLFC$log2FoldChange.6mo, color = res$lfcSE) + scale_color_viridis_c(name = "res$lfcSE", trans = "log")

```





```

